# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LifeSimu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LifeSimu(object):
    def setupUi(self, LifeSimu):
        LifeSimu.setObjectName("LifeSimu")
        LifeSimu.resize(900, 660)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(LifeSimu.sizePolicy().hasHeightForWidth())
        LifeSimu.setSizePolicy(sizePolicy)
        LifeSimu.setMinimumSize(QtCore.QSize(900, 620))
        self.LSimucentralwidget = QtWidgets.QWidget(LifeSimu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LSimucentralwidget.sizePolicy().hasHeightForWidth())
        self.LSimucentralwidget.setSizePolicy(sizePolicy)
        self.LSimucentralwidget.setObjectName("LSimucentralwidget")
        self.LSimu_SRV_Group = QtWidgets.QGroupBox(self.LSimucentralwidget)
        self.LSimu_SRV_Group.setGeometry(QtCore.QRect(20, 140, 311, 131))
        self.LSimu_SRV_Group.setObjectName("LSimu_SRV_Group")
        self.radioButton_CJ0 = QtWidgets.QRadioButton(self.LSimu_SRV_Group)
        self.radioButton_CJ0.setGeometry(QtCore.QRect(10, 45, 111, 31))
        self.radioButton_CJ0.setChecked(True)
        self.radioButton_CJ0.setObjectName("radioButton_CJ0")
        self.label_2 = QtWidgets.QLabel(self.LSimu_SRV_Group)
        self.label_2.setGeometry(QtCore.QRect(210, 50, 41, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_thickness = QtWidgets.QLineEdit(self.LSimu_SRV_Group)
        self.lineEdit_thickness.setGeometry(QtCore.QRect(130, 80, 71, 20))
        self.lineEdit_thickness.setObjectName("lineEdit_thickness")
        self.lineEdit_CSRV = QtWidgets.QLineEdit(self.LSimu_SRV_Group)
        self.lineEdit_CSRV.setGeometry(QtCore.QRect(130, 20, 71, 20))
        self.lineEdit_CSRV.setObjectName("lineEdit_CSRV")
        self.radioButton_CSRV = QtWidgets.QRadioButton(self.LSimu_SRV_Group)
        self.radioButton_CSRV.setGeometry(QtCore.QRect(10, 13, 111, 31))
        self.radioButton_CSRV.setChecked(False)
        self.radioButton_CSRV.setObjectName("radioButton_CSRV")
        self.lineEdit_Cj0 = QtWidgets.QLineEdit(self.LSimu_SRV_Group)
        self.lineEdit_Cj0.setGeometry(QtCore.QRect(130, 50, 71, 20))
        self.lineEdit_Cj0.setObjectName("lineEdit_Cj0")
        self.label = QtWidgets.QLabel(self.LSimu_SRV_Group)
        self.label.setGeometry(QtCore.QRect(210, 20, 31, 20))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.LSimu_SRV_Group)
        self.label_3.setGeometry(QtCore.QRect(30, 83, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.LSimu_SRV_Group)
        self.label_6.setGeometry(QtCore.QRect(210, 84, 47, 10))
        self.label_6.setObjectName("label_6")
        self.radioButton_nosrv = QtWidgets.QRadioButton(self.LSimu_SRV_Group)
        self.radioButton_nosrv.setGeometry(QtCore.QRect(10, 102, 82, 17))
        self.radioButton_nosrv.setObjectName("radioButton_nosrv")
        self.groupBox_2 = QtWidgets.QGroupBox(self.LSimucentralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 311, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_n = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_n.setGeometry(QtCore.QRect(200, 20, 82, 17))
        self.radioButton_n.setChecked(False)
        self.radioButton_n.setObjectName("radioButton_n")
        self.radioButton_p = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_p.setGeometry(QtCore.QRect(200, 40, 82, 17))
        self.radioButton_p.setChecked(True)
        self.radioButton_p.setObjectName("radioButton_p")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_4.setObjectName("label_4")
        self.lineEdit_Ndop = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Ndop.setGeometry(QtCore.QRect(20, 40, 91, 20))
        self.lineEdit_Ndop.setObjectName("lineEdit_Ndop")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(120, 40, 31, 21))
        self.label_5.setObjectName("label_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.LSimucentralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 280, 311, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 40, 41, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 80, 51, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 120, 51, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 160, 41, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(20, 200, 101, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_Et_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Et_1.setGeometry(QtCore.QRect(10, 60, 91, 20))
        self.lineEdit_Et_1.setObjectName("lineEdit_Et_1")
        self.lineEdit_sign_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_sign_1.setGeometry(QtCore.QRect(10, 100, 91, 20))
        self.lineEdit_sign_1.setObjectName("lineEdit_sign_1")
        self.lineEdit_sigp_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_sigp_1.setGeometry(QtCore.QRect(10, 140, 91, 20))
        self.lineEdit_sigp_1.setObjectName("lineEdit_sigp_1")
        self.lineEdit_Nt_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Nt_1.setGeometry(QtCore.QRect(10, 180, 91, 20))
        self.lineEdit_Nt_1.setObjectName("lineEdit_Nt_1")
        self.lineEdit_taun_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_taun_1.setGeometry(QtCore.QRect(10, 220, 91, 20))
        self.lineEdit_taun_1.setReadOnly(True)
        self.lineEdit_taun_1.setObjectName("lineEdit_taun_1")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(110, 60, 21, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(110, 100, 21, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(110, 140, 21, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(110, 180, 31, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(110, 220, 31, 21))
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(170, 40, 41, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(260, 180, 31, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(260, 100, 21, 21))
        self.label_27.setObjectName("label_27")
        self.lineEdit_sigp_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_sigp_2.setGeometry(QtCore.QRect(160, 140, 91, 20))
        self.lineEdit_sigp_2.setObjectName("lineEdit_sigp_2")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(170, 200, 101, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_Nt_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Nt_2.setGeometry(QtCore.QRect(160, 180, 91, 20))
        self.lineEdit_Nt_2.setObjectName("lineEdit_Nt_2")
        self.lineEdit_taun_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_taun_2.setGeometry(QtCore.QRect(160, 220, 91, 20))
        self.lineEdit_taun_2.setReadOnly(True)
        self.lineEdit_taun_2.setObjectName("lineEdit_taun_2")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(170, 80, 51, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(260, 140, 21, 21))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(170, 160, 41, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setGeometry(QtCore.QRect(260, 220, 31, 21))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(260, 60, 21, 21))
        self.label_33.setObjectName("label_33")
        self.lineEdit_Et_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Et_2.setGeometry(QtCore.QRect(160, 60, 91, 20))
        self.lineEdit_Et_2.setObjectName("lineEdit_Et_2")
        self.lineEdit_sign_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_sign_2.setGeometry(QtCore.QRect(160, 100, 91, 20))
        self.lineEdit_sign_2.setObjectName("lineEdit_sign_2")
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setGeometry(QtCore.QRect(170, 120, 51, 16))
        self.label_34.setObjectName("label_34")
        self.checkBox_1stDefect = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_1stDefect.setGeometry(QtCore.QRect(12, 20, 81, 17))
        self.checkBox_1stDefect.setChecked(True)
        self.checkBox_1stDefect.setObjectName("checkBox_1stDefect")
        self.checkBox_2ndDefect = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2ndDefect.setGeometry(QtCore.QRect(160, 20, 91, 17))
        self.checkBox_2ndDefect.setChecked(True)
        self.checkBox_2ndDefect.setObjectName("checkBox_2ndDefect")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 240, 101, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(170, 241, 101, 16))
        self.label_24.setObjectName("label_24")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(260, 256, 31, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(110, 256, 31, 21))
        self.label_36.setObjectName("label_36")
        self.lineEdit_taup_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_taup_2.setGeometry(QtCore.QRect(160, 256, 91, 20))
        self.lineEdit_taup_2.setReadOnly(True)
        self.lineEdit_taup_2.setObjectName("lineEdit_taup_2")
        self.lineEdit_taup_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_taup_1.setGeometry(QtCore.QRect(10, 256, 91, 20))
        self.lineEdit_taup_1.setReadOnly(True)
        self.lineEdit_taup_1.setObjectName("lineEdit_taup_1")
        self.checkBox_dorid = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_dorid.setGeometry(QtCore.QRect(10, 280, 131, 20))
        self.checkBox_dorid.setObjectName("checkBox_dorid")
        self.label_10 = QtWidgets.QLabel(self.LSimucentralwidget)
        self.label_10.setGeometry(QtCore.QRect(480, 30, 61, 16))
        self.label_10.setObjectName("label_10")
        self.comboBox_plotopt = QtWidgets.QComboBox(self.LSimucentralwidget)
        self.comboBox_plotopt.setGeometry(QtCore.QRect(480, 60, 131, 21))
        self.comboBox_plotopt.setObjectName("comboBox_plotopt")
        self.comboBox_plotopt.addItem("")
        self.comboBox_plotopt.addItem("")
        self.comboBox_plotopt.addItem("")
        self.comboBox_plotopt.addItem("")
        self.label_8 = QtWidgets.QLabel(self.LSimucentralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 590, 121, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.LSimucentralwidget)
        self.label_9.setGeometry(QtCore.QRect(130, 610, 21, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_temp = QtWidgets.QLineEdit(self.LSimucentralwidget)
        self.lineEdit_temp.setGeometry(QtCore.QRect(30, 610, 91, 20))
        self.lineEdit_temp.setObjectName("lineEdit_temp")
        self.label_21 = QtWidgets.QLabel(self.LSimucentralwidget)
        self.label_21.setGeometry(QtCore.QRect(350, 30, 61, 16))
        self.label_21.setObjectName("label_21")
        self.comboBox_plottype = QtWidgets.QComboBox(self.LSimucentralwidget)
        self.comboBox_plottype.setGeometry(QtCore.QRect(350, 60, 101, 21))
        self.comboBox_plottype.setObjectName("comboBox_plottype")
        self.comboBox_plottype.addItem("")
        self.comboBox_plottype.addItem("")
        self.checkBox_int = QtWidgets.QCheckBox(self.LSimucentralwidget)
        self.checkBox_int.setGeometry(QtCore.QRect(680, 50, 70, 17))
        self.checkBox_int.setChecked(True)
        self.checkBox_int.setObjectName("checkBox_int")
        self.checkBox_SRV = QtWidgets.QCheckBox(self.LSimucentralwidget)
        self.checkBox_SRV.setGeometry(QtCore.QRect(680, 70, 70, 17))
        self.checkBox_SRV.setChecked(True)
        self.checkBox_SRV.setObjectName("checkBox_SRV")
        self.checkBox_SRH = QtWidgets.QCheckBox(self.LSimucentralwidget)
        self.checkBox_SRH.setGeometry(QtCore.QRect(760, 50, 70, 17))
        self.checkBox_SRH.setChecked(True)
        self.checkBox_SRH.setObjectName("checkBox_SRH")
        self.checkBox_eff = QtWidgets.QCheckBox(self.LSimucentralwidget)
        self.checkBox_eff.setGeometry(QtCore.QRect(760, 70, 70, 17))
        self.checkBox_eff.setChecked(True)
        self.checkBox_eff.setObjectName("checkBox_eff")
        self.label_22 = QtWidgets.QLabel(self.LSimucentralwidget)
        self.label_22.setGeometry(QtCore.QRect(190, 590, 81, 16))
        self.label_22.setObjectName("label_22")
        self.label_7 = QtWidgets.QLabel(self.LSimucentralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 610, 31, 21))
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.lineEdit_nxc = QtWidgets.QLineEdit(self.LSimucentralwidget)
        self.lineEdit_nxc.setGeometry(QtCore.QRect(180, 610, 91, 20))
        self.lineEdit_nxc.setObjectName("lineEdit_nxc")
        self.pushButton_plot = QtWidgets.QPushButton(self.LSimucentralwidget)
        self.pushButton_plot.setGeometry(QtCore.QRect(380, 600, 181, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plot.sizePolicy().hasHeightForWidth())
        self.pushButton_plot.setSizePolicy(sizePolicy)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.LSimucentralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 100, 541, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_exp = QtWidgets.QPushButton(self.LSimucentralwidget)
        self.pushButton_exp.setGeometry(QtCore.QRect(700, 600, 75, 31))
        self.pushButton_exp.setObjectName("pushButton_exp")
        self.groupBox = QtWidgets.QGroupBox(self.LSimucentralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 311, 41))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_nointrin = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_nointrin.setGeometry(QtCore.QRect(10, 16, 101, 17))
        self.radioButton_nointrin.setObjectName("radioButton_nointrin")
        LifeSimu.setCentralWidget(self.LSimucentralwidget)

        self.retranslateUi(LifeSimu)
        QtCore.QMetaObject.connectSlotsByName(LifeSimu)

    def retranslateUi(self, LifeSimu):
        _translate = QtCore.QCoreApplication.translate
        LifeSimu.setWindowTitle(_translate("LifeSimu", "MainWindow"))
        self.LSimu_SRV_Group.setTitle(_translate("LifeSimu", "Surface"))
        self.radioButton_CJ0.setText(_translate("LifeSimu", "Constant j0\n"
"(sum of both sides)"))
        self.label_2.setText(_translate("LifeSimu", "<html><head/><body><p>fA/cm<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.lineEdit_thickness.setText(_translate("LifeSimu", "0.018"))
        self.lineEdit_CSRV.setText(_translate("LifeSimu", "10"))
        self.radioButton_CSRV.setText(_translate("LifeSimu", "Constant SRV\n"
"(sum of both sides)"))
        self.lineEdit_Cj0.setText(_translate("LifeSimu", "10"))
        self.label.setText(_translate("LifeSimu", "cm/s"))
        self.label_3.setText(_translate("LifeSimu", "Thickness"))
        self.label_6.setText(_translate("LifeSimu", "cm"))
        self.radioButton_nosrv.setText(_translate("LifeSimu", "No SRV"))
        self.groupBox_2.setTitle(_translate("LifeSimu", "Sample"))
        self.radioButton_n.setText(_translate("LifeSimu", "n-type"))
        self.radioButton_p.setText(_translate("LifeSimu", "p-type"))
        self.label_4.setText(_translate("LifeSimu", "Ndop"))
        self.lineEdit_Ndop.setText(_translate("LifeSimu", "1e16"))
        self.label_5.setText(_translate("LifeSimu", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">-3</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("LifeSimu", "Defect"))
        self.label_11.setText(_translate("LifeSimu", "Et"))
        self.label_12.setText(_translate("LifeSimu", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">n</span></p></body></html>"))
        self.label_13.setText(_translate("LifeSimu", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">p</span></p></body></html>"))
        self.label_14.setText(_translate("LifeSimu", "Nt"))
        self.label_15.setText(_translate("LifeSimu", "<html><head/><body><p>τ<span style=\" vertical-align:sub;\">n1</span></p></body></html>"))
        self.lineEdit_Et_1.setText(_translate("LifeSimu", "0"))
        self.lineEdit_sign_1.setText(_translate("LifeSimu", "1e-13"))
        self.lineEdit_sigp_1.setText(_translate("LifeSimu", "1e-13"))
        self.lineEdit_Nt_1.setText(_translate("LifeSimu", "1e12"))
        self.label_16.setText(_translate("LifeSimu", "eV"))
        self.label_17.setText(_translate("LifeSimu", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.label_18.setText(_translate("LifeSimu", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.label_19.setText(_translate("LifeSimu", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">-3</span></p></body></html>"))
        self.label_20.setText(_translate("LifeSimu", "s"))
        self.label_25.setText(_translate("LifeSimu", "Et"))
        self.label_26.setText(_translate("LifeSimu", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">-3</span></p></body></html>"))
        self.label_27.setText(_translate("LifeSimu", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.lineEdit_sigp_2.setText(_translate("LifeSimu", "1e-13"))
        self.label_28.setText(_translate("LifeSimu", "<html><head/><body><p>τ<span style=\" vertical-align:sub;\">n2</span></p></body></html>"))
        self.lineEdit_Nt_2.setText(_translate("LifeSimu", "1e12"))
        self.label_29.setText(_translate("LifeSimu", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">n</span></p></body></html>"))
        self.label_30.setText(_translate("LifeSimu", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.label_31.setText(_translate("LifeSimu", "Nt"))
        self.label_32.setText(_translate("LifeSimu", "s"))
        self.label_33.setText(_translate("LifeSimu", "eV"))
        self.lineEdit_Et_2.setText(_translate("LifeSimu", "0.4"))
        self.lineEdit_sign_2.setText(_translate("LifeSimu", "1e-13"))
        self.label_34.setText(_translate("LifeSimu", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">p</span></p></body></html>"))
        self.checkBox_1stDefect.setText(_translate("LifeSimu", "First defect"))
        self.checkBox_2ndDefect.setText(_translate("LifeSimu", "Second defect"))
        self.label_23.setText(_translate("LifeSimu", "<html><head/><body><p>τ<span style=\" vertical-align:sub;\">p1</span></p></body></html>"))
        self.label_24.setText(_translate("LifeSimu", "<html><head/><body><p>τ<span style=\" vertical-align:sub;\">p2</span></p></body></html>"))
        self.label_35.setText(_translate("LifeSimu", "s"))
        self.label_36.setText(_translate("LifeSimu", "s"))
        self.checkBox_dorid.setText(_translate("LifeSimu", "Two dependent levels"))
        self.label_10.setText(_translate("LifeSimu", "Plot option"))
        self.comboBox_plotopt.setItemText(0, _translate("LifeSimu", "Lifetime vs nxc"))
        self.comboBox_plotopt.setItemText(1, _translate("LifeSimu", "Inverse lifetime vs nxc"))
        self.comboBox_plotopt.setItemText(2, _translate("LifeSimu", "Lifetime vs X(Y)"))
        self.comboBox_plotopt.setItemText(3, _translate("LifeSimu", "Inverse lifetime vs X(Y)"))
        self.label_8.setText(_translate("LifeSimu", "Temperature (for IDLS)"))
        self.label_9.setText(_translate("LifeSimu", "K"))
        self.lineEdit_temp.setText(_translate("LifeSimu", "300"))
        self.label_21.setText(_translate("LifeSimu", "Plot Type"))
        self.comboBox_plottype.setItemText(0, _translate("LifeSimu", "IDLS"))
        self.comboBox_plottype.setItemText(1, _translate("LifeSimu", "TDLS"))
        self.checkBox_int.setText(_translate("LifeSimu", "Intrinsic"))
        self.checkBox_SRV.setText(_translate("LifeSimu", "Surface"))
        self.checkBox_SRH.setText(_translate("LifeSimu", "Defect"))
        self.checkBox_eff.setText(_translate("LifeSimu", "Effective"))
        self.label_22.setText(_translate("LifeSimu", "<html><head/><body><p>Δn (for TDLS)</p></body></html>"))
        self.label_7.setText(_translate("LifeSimu", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">-3</span></p></body></html>"))
        self.lineEdit_nxc.setText(_translate("LifeSimu", "1e12"))
        self.pushButton_plot.setText(_translate("LifeSimu", "PLOT!"))
        self.pushButton_exp.setText(_translate("LifeSimu", "Export"))
        self.groupBox.setTitle(_translate("LifeSimu", "Intrinsic"))
        self.radioButton_nointrin.setText(_translate("LifeSimu", "No intrinsic"))

