# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LifetimeMain.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LSanalyzer(object):
    def setupUi(self, LSanalyzer):
        LSanalyzer.setObjectName("LSanalyzer")
        LSanalyzer.resize(279, 337)
        self.Maincentralwidget = QtWidgets.QWidget(LSanalyzer)
        self.Maincentralwidget.setObjectName("Maincentralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Maincentralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainLayout = QtWidgets.QVBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.MainlifesimuPushB = QtWidgets.QPushButton(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainlifesimuPushB.sizePolicy().hasHeightForWidth())
        self.MainlifesimuPushB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.MainlifesimuPushB.setFont(font)
        self.MainlifesimuPushB.setObjectName("MainlifesimuPushB")
        self.MainLayout.addWidget(self.MainlifesimuPushB)
        self.MainIDLSPushB = QtWidgets.QPushButton(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainIDLSPushB.sizePolicy().hasHeightForWidth())
        self.MainIDLSPushB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.MainIDLSPushB.setFont(font)
        self.MainIDLSPushB.setObjectName("MainIDLSPushB")
        self.MainLayout.addWidget(self.MainIDLSPushB)
        self.MainTDLSPushB = QtWidgets.QPushButton(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainTDLSPushB.sizePolicy().hasHeightForWidth())
        self.MainTDLSPushB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.MainTDLSPushB.setFont(font)
        self.MainTDLSPushB.setObjectName("MainTDLSPushB")
        self.MainLayout.addWidget(self.MainTDLSPushB)
        self.MainAboutPushB = QtWidgets.QPushButton(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainAboutPushB.sizePolicy().hasHeightForWidth())
        self.MainAboutPushB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.MainAboutPushB.setFont(font)
        self.MainAboutPushB.setObjectName("MainAboutPushB")
        self.MainLayout.addWidget(self.MainAboutPushB)
        self.verticalLayout.addLayout(self.MainLayout)
        LSanalyzer.setCentralWidget(self.Maincentralwidget)
        self.actionni = QtWidgets.QAction(LSanalyzer)
        self.actionni.setObjectName("actionni")
        self.actionB = QtWidgets.QAction(LSanalyzer)
        self.actionB.setObjectName("actionB")
        self.actionionisation = QtWidgets.QAction(LSanalyzer)
        self.actionionisation.setObjectName("actionionisation")
        self.actionThermal_velocity = QtWidgets.QAction(LSanalyzer)
        self.actionThermal_velocity.setObjectName("actionThermal_velocity")
        self.actionAltermatt2005 = QtWidgets.QAction(LSanalyzer)
        self.actionAltermatt2005.setObjectName("actionAltermatt2005")
        self.actionTrupke2003 = QtWidgets.QAction(LSanalyzer)
        self.actionTrupke2003.setObjectName("actionTrupke2003")
        self.actionRichter2012 = QtWidgets.QAction(LSanalyzer)
        self.actionRichter2012.setObjectName("actionRichter2012")
        self.actionKerr2002_simple = QtWidgets.QAction(LSanalyzer)
        self.actionKerr2002_simple.setObjectName("actionKerr2002_simple")
        self.actionKerr2002_complex = QtWidgets.QAction(LSanalyzer)
        self.actionKerr2002_complex.setObjectName("actionKerr2002_complex")
        self.actionGlunz1999 = QtWidgets.QAction(LSanalyzer)
        self.actionGlunz1999.setObjectName("actionGlunz1999")
        self.actionAltermatt1997 = QtWidgets.QAction(LSanalyzer)
        self.actionAltermatt1997.setObjectName("actionAltermatt1997")
        self.actionCouderc2014 = QtWidgets.QAction(LSanalyzer)
        self.actionCouderc2014.setObjectName("actionCouderc2014")
        self.actionGreen1990_full = QtWidgets.QAction(LSanalyzer)
        self.actionGreen1990_full.setObjectName("actionGreen1990_full")
        self.actionGreen1990_param = QtWidgets.QAction(LSanalyzer)
        self.actionGreen1990_param.setObjectName("actionGreen1990_param")
        self.actionYan2014fer = QtWidgets.QAction(LSanalyzer)
        self.actionYan2014fer.setObjectName("actionYan2014fer")
        self.actionDelAlamo1985 = QtWidgets.QAction(LSanalyzer)
        self.actionDelAlamo1985.setObjectName("actionDelAlamo1985")
        self.actionCuevas1996 = QtWidgets.QAction(LSanalyzer)
        self.actionCuevas1996.setObjectName("actionCuevas1996")

        self.retranslateUi(LSanalyzer)
        QtCore.QMetaObject.connectSlotsByName(LSanalyzer)

    def retranslateUi(self, LSanalyzer):
        _translate = QtCore.QCoreApplication.translate
        LSanalyzer.setWindowTitle(_translate("LSanalyzer", "MainWindow"))
        self.MainlifesimuPushB.setText(_translate("LSanalyzer", "Lifetime simulator"))
        self.MainIDLSPushB.setText(_translate("LSanalyzer", "TIDLS and Ndop-IDLS"))
        self.MainTDLSPushB.setText(_translate("LSanalyzer", "TDLS"))
        self.MainAboutPushB.setText(_translate("LSanalyzer", "About"))
        self.actionni.setText(_translate("LSanalyzer", "ni"))
        self.actionB.setText(_translate("LSanalyzer", "Bandgap"))
        self.actionionisation.setText(_translate("LSanalyzer", "ionisation"))
        self.actionThermal_velocity.setText(_translate("LSanalyzer", "Thermal velocity"))
        self.actionAltermatt2005.setText(_translate("LSanalyzer", "Altermatt2005"))
        self.actionTrupke2003.setText(_translate("LSanalyzer", "Trupke2003"))
        self.actionRichter2012.setText(_translate("LSanalyzer", "Richter2012"))
        self.actionKerr2002_simple.setText(_translate("LSanalyzer", "Kerr2002_simple"))
        self.actionKerr2002_complex.setText(_translate("LSanalyzer", "Kerr2002_complex"))
        self.actionGlunz1999.setText(_translate("LSanalyzer", "Glunz1999"))
        self.actionAltermatt1997.setText(_translate("LSanalyzer", "Altermatt1997"))
        self.actionCouderc2014.setText(_translate("LSanalyzer", "Couderc2014"))
        self.actionGreen1990_full.setText(_translate("LSanalyzer", "Green1990_full"))
        self.actionGreen1990_param.setText(_translate("LSanalyzer", "Green1990_param"))
        self.actionYan2014fer.setText(_translate("LSanalyzer", "Yan2014fer"))
        self.actionDelAlamo1985.setText(_translate("LSanalyzer", "DelAlamo1985"))
        self.actionCuevas1996.setText(_translate("LSanalyzer", "Cuevas1996"))

